title: Happyaeorg
description: Website grup happyae
url: https://happyaeorg.github.io
baseurl: /www
permalink: pretty
timezone: Asia/Jakarta
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
author:
  name: Happyaeorg
  email: happyaeorg@gmail.com
